# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('username', models.CharField(default='', max_length=200)),
                ('states', models.IntegerField(default=-1)),
                ('uva_id', models.CharField(default='', max_length=200)),
                ('uva_passwd', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
